# Generated by Django 2.2.5 on 2020-12-14 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetInfo',
            fields=[
                ('serial_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('p_password', models.CharField(max_length=20)),
                ('temprature', models.IntegerField()),
                ('gps', models.CharField(max_length=20)),
                ('heart_rate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserPet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connectapp.PetInfo')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connectapp.UserInfo')),
            ],
        ),
    ]
